### ISSUE TITLE
windows平台运行时总是显示permission deny 

### ISSUE THREAD

**Issue by Genwei-Zhang** [zkyseu/PPlanedet#10]
您好，我在安装过程都挺顺利，但是无论是在训练或者推断的时候都会出现一个PermissionError, 长这样：

`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\genwe\\AppData\\Local\\Temp\\tmp8vlqnvn3\\tmplpyzwhyo.py'`

显示的是tools/detect.py里这行代码所致：

`with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:`

我在您库里直接下载了CLRNet的训练权重model.pd.
运行推断的命令是：

`python tools/detect.py configs/clrnet/resnet34_culane.py --img data\test_data\road_image.png --load_from trained_models\resnet34_culine_pretrained\model.pd --savedir data\test_data\output`

我也试过用管理员模式运行，但是我一直得到这个错误，请问是这个detect.py尝试往这个local/temp文件夹里写入什么东西才导致被拒的吗？我应该如何绕过，或者修改script才能成功的使用预训练模型推断单张图片呢。

还请不吝赐教。

整体报错长这样:

> C:\software\anaconda3\envs\pplanedet\lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\software\anaconda3\envs\pplanedet\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\software\anaconda3\envs\pplanedet\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\software\anaconda3\envs\pplanedet\lib\site-packages\albumentations\augmentations\geometric\functional.py:7: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
C:\software\anaconda3\envs\pplanedet\lib\site-packages\albumentations\augmentations\transforms.py:14: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
Traceback (most recent call last):
  File "tools/detect.py", line 190, in <module>
    process(args)
  File "tools/detect.py", line 172, in process
    cfg = Config.fromfile(args.config)
  File "c:\users\genwe\onedrive\desktop\projects\traffic_light\real_camera_tsc\lane_detection\pplanedet-5\pplanedet\utils\py_config.py", line 178, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "c:\users\genwe\onedrive\desktop\projects\traffic_light\real_camera_tsc\lane_detection\pplanedet-5\pplanedet\utils\py_config.py", line 103, in _file2dict
    shutil.copyfile(filename,
  File "C:\software\anaconda3\envs\pplanedet\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\genwe\\AppData\\Local\\Temp\\tmp8vlqnvn3\\tmplpyzwhyo.py'

**Comment by Genwei-Zhang** [comment]
请问是否有可能是detect.py里有只能在Linux系统上运行的命令所以windows这边会报错吗？

**Comment by zkyseu** [comment]
@Genwei-Zhang 您好，您是否用Pycharm这种客户端运行？如果是，改成用命令行运行哈

**Comment by zkyseu** [comment]
PPLanedet确实在Windows上会有些问题，但也不是绝对的，Windows命令行也还是可以的，

**Comment by Genwei-Zhang** [comment]
我确实是在windows CMD 和windows Anconda PowerShell 都试过，会出现同样的问题。如果确实不行的话，我去试试Linux的环境，您是以Linux环境为基础测试的对吗？
________________________________

**Comment by zkyseu** [comment]
@Genwei-Zhang 对的哈，Linux是可以正常运行的，您也可以到百度aistudio上运行我们的项目来测试效果。

**Comment by Qiuyanghang** [comment]
您好，我在Windows系统下运行也遇到了一样的问题，请问在Windows系统运行有什么解决方法？（管理员模式和命令行运行试过还是一样的问题）
望作者回复，十分感激！！


> @Genwei-Zhang 您好，您是否用Pycharm这种客户端运行？如果是，改成用命令行运行哈

**Comment by zkyredstart** [comment]
您好，目前windows上面运行确实会出现权限不允许问题，这个是由于windows无法写入临时文件，但是Linux可以，这个错误我还没有想到解决办法因为我手头上还没有windows的gpu机器，如果您解决了或者提供了一些中间报错过程，我可以协助你。

**Comment by Qiuyanghang** [comment]
> 您好，目前windows上面运行确实会出现权限不允许问题，这个是由于windows无法写入临时文件，但是Linux可以，这个错误我还没有想到解决办法因为我手头上还没有windows的gpu机器，如果您解决了或者提供了一些中间报错过程，我可以协助你。

十分感谢回复！中间报错过程和这位题主是一样的，还正在尝试解决，如后续还是不行我去linux环境下测试。
