### ISSUE TITLE
Great project, I want to ask a question， How to export onnx model?

### ISSUE THREAD

**Issue by Byronnar** [zkyseu/PPlanedet#16]
Great project, I want to ask a question， How to export onnx model?

**Comment by Byronnar** [comment]
ADNet，@zkyseu, Thank u

**Comment by zkyseu** [comment]
Hi. I do not try the onnx export for PPLanedet. I think it is a useful tool for inference. I will try it in the following days.

**Comment by Byronnar** [comment]
> Hi. I do not try the onnx export for PPLanedet. I think it is a useful tool for inference. I will try it in the following days.

ok, thanks
