### ISSUE TITLE
训练condlane时报错

### ISSUE THREAD

**Issue by yuxuanchai** [zkyseu/PPlanedet#2]
<img width="1280" alt="1679902396846" src="https://user-images.githubusercontent.com/110382305/227871887-2e70d2eb-aed2-40e9-a019-eb27cd45bec1.png">
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\83809\\AppData\\Local\\Temp\\tmp8h5xag6e\\tmpxnn_wbqm.py'

在文件夹中找不到这个报错文件。
每一次报错这个.py文件的名称还不一样。

请问有遇到过同样问题吗？

**Comment by zkyseu** [comment]
@yuxuanchai 你好，你是直接运行train.py中吗，还是在终端运行命令执行的？如果在终端命令的话方便提供一下运行的命令吗

**Comment by zkyseu** [comment]
@yuxuanchai 这里建议你在windows powershell里面的shell界面里面按照readme文件里面步骤运行shell命令，这样应该可以正常运行哈

**Comment by yuxuanchai** [comment]
> @yuxuanchai 这里建议你在Windows powershell里面的shell界面里面按照readme文件里面步骤运行shell命令，这样应该可以正常运行哈
您好，感谢回答。我是在pycharm中直接运行的train.py  形参是-c configs/condlane/resnet50_culane.py

<img width="1280" alt="1679969859429" src="https://user-images.githubusercontent.com/110382305/228110030-2eb4c66a-87aa-4f82-b6f1-16eda3afe776.png">
同样的问题我也在condlanenet的源码中遇到过

尝试了在powershell中操作也遇到了同样的问题，python tools/train.py -c configs/condlane/resnet50_culane.py

<img width="1280" alt="d0245c2e61619009582535f9249433b" src="https://user-images.githubusercontent.com/110382305/228112458-75a1ccd9-73fd-4d0f-9999-95fecbd4028b.png">

**Comment by zkyseu** [comment]
@yuxuanchai 我看了一下哈，因为我手头上只有linux的电脑没有Windows的，无法准确定位到你的错误。但是可以按照以下方法尝试看能否解决:
1、将 `\\` 替换成 `/` 看是否能够成功；
2、如果(1)无法成功，应该是shutil库无法在c盘进行操作，可以换成`os.system("cp 需要复制的文件路径 目标文件夹")`，其中cp是linux中shell指令里面复制文件的命令，并且文件路径需要"/"进行连接。

**Comment by yuxuanchai** [comment]
> @yuxuanchai 我看了一下哈，因为我手头上只有linux的电脑没有Windows的，无法准确定位到你的错误。但是可以按照以下方法尝试看能否解决: 1、将 `\\` 替换成 `/` 看是否能够成功； 2、如果(1)无法成功，应该是shutil库无法在c盘进行操作，可以换成`os.system("cp 需要复制的文件路径 目标文件夹")`，其中cp是linux中shell指令里面复制文件的命令，并且文件路径需要"/"进行连接。

按照您提供的方法我解决了这个问题，但在windows系统运行还是存在其他权限问题。
我打算换个linux系统再尝试运行
感谢您的解答！

**Comment by zkyseu** [comment]
@yuxuanchai  好的，如果您有其他问题欢迎重新打开这个issue哈
