### ISSUE TITLE
关于动态分配里分类成本的计算问题

### ISSUE THREAD

**Issue by Core9724** [zkyseu/PPlanedet#4]
作者您好！我想请教一下在pplanedet/model/common_model/dynamic_assign.py里关于分类成本focal_cost计算，这个是不是只是针对背景/车道线两个类别？如果我现在希望对背景/实线/虚线进行区分，在这里我是否还需要做一些修改？另外还想请教一下在多分类的时候例如背景/实线/虚线，正负样本该怎么定义呢？是实线虚线都算正样本吗？
感谢百忙之余抽空查看，还望不吝赐教！

**Comment by zkyseu** [comment]
@UcasCore 您好，我不清楚您的虚线是否包含斑马线这种。通常来说，您可以将虚线和实线当作不同的车道线。这二者均为前景。然后动态分配里面的代码是不需要修改的，因为他是对每个类别进行正负样本分配。只需要定义好车道线的类别即可。其实您的实线和虚线可以参考CULane里面将每条这车道线都作为不同的实例来考虑。
另外，动态分配其实和目标检测里面的动态分配思路是一致的，您也可以参考目标检测里面标签分配的思路。

**Comment by Core9724** [comment]
明白了，感谢指教！
