### ISSUE TITLE
测试clrnet时出现问题

### ISSUE THREAD

**Issue by billionon** [zkyseu/PPlanedet#7]
执行detect.py脚本，运行到clr_head.py中第437行时卡住
![屏幕截图 2023-12-14 152128](https://github.com/zkyseu/PPlanedet/assets/75113154/fe1ba903-b30d-4efb-b3db-9ea75eced3f9)

**Comment by zkyseu** [comment]
@billionon 我晚些时候来测试一下，争取今天晚上给您反馈哈。

**Comment by zkyseu** [comment]
@billionon 您好，我刚刚运行了一下detect.py 默认用clenet culane 权重可以正常运行。
![image](https://github.com/zkyseu/PPlanedet/assets/118790294/fdc13d93-82b6-40b5-bb6e-f4ab722405c6)

我建议检测一下paddlepaddle是否正常安装，另外检查是否可以正常训练和eval，一般可以eval就可以detect。
