### ISSUE TITLE
未找到预训练模型权重

### ISSUE THREAD

**Issue by TaoZex** [zkyseu/PPlanedet#8]
The pretrain weight of the CondLaneNet network is not found in the repo, will it be provided? Thank you.

**Comment by zkyseu** [comment]
Hi, [here](https://github.com/zkyseu/PPlanedet/tree/v5/configs/condlane) is the pretrain weight of the CondLaneNet.

**Comment by TaoZex** [comment]
> Hi, [here](https://github.com/zkyseu/PPlanedet/tree/v5/configs/condlane) is the pretrain weight of the CondLaneNet.

Thank you for your help. It helped me a lot.

**Comment by TaoZex** [comment]
Hello, @zkyseu.I used the weights trained by backbone for CSPResNetm from https://github.com/zkyseu/PPlanedet/tree/v5/configs/condlane, and the result was 79.76, which is lower than the annotated result (F1: 79.92) , what causes this? Looking forward to your reply.

**Comment by zkyseu** [comment]
The CondLaneNet is trained on a single 3090 GPU. Could you provide your training information? Thanks!

**Comment by TaoZex** [comment]
> The CondLaneNet is trained on a single 3090 GPU. Could you provide your training information? Thanks!

cuda：11.6
cudnn：cudnn-linux-x86_64-8.4.0.27
gpu：single 4090
python：3.8.18

Thanks for your reply, this is the configuration I used.

**Comment by zkyseu** [comment]
Hi, could you reproduce the annotated result (79.92% F1 score) using the provided weight?

**Comment by TaoZex** [comment]
> Hi, could you reproduce the annotated result (79.92% F1 score) using the provided weight?

Thanks. I have reproduced it. In addition, I found in the visualization that the image annotation results are similar to the following (annotated with blue dots) :
![b1af8ca55432cb6f0dfe1e8a3a498fc](https://github.com/zkyseu/PPlanedet/assets/45089228/05d901ec-558e-4254-927a-e89901d9c8c1)
In general, it should look like this:
![af6f9fe5f736b21650027884ea6f486](https://github.com/zkyseu/PPlanedet/assets/45089228/2f5a9585-449a-4204-9cda-4953b837bc3c)
Will this visualization be provided in the repo? Look forward to hearing from you.

**Comment by zkyseu** [comment]
@TaoZex Hi, you can just use `cv2.line` to generate the visualization result you want. I will consider adding this visualization result in the future. I was busy with my project recently.

**Comment by zkyseu** [comment]
The visualization code is [here](https://github.com/zkyseu/PPlanedet/blob/v5/pplanedet/datasets/visualization.py).

**Comment by zkyseu** [comment]
I closed this issue. If you have a new question, please reopen this issue.

**Comment by TaoZex** [comment]
> The visualization code is [here](https://github.com/zkyseu/PPlanedet/blob/v5/pplanedet/datasets/visualization.py).

Thanks for your reply. Good luck with your project!
