### ISSUE TITLE
想问一下作者有没有在windows 平台测试过，我这边windows cpu paddle 2.4 库里的代码没有一个可以运行出结果的。

### ISSUE THREAD

**Issue by hao1305430263** [zkyseu/PPlanedet#9]
想问一下作者有没有在windows 平台测试过，我这边windows cpu paddle 2.4.2 库里的代码**没有一个**可以运行出结果的。要不然就是参数不全，要不然就是config 出错。
![image](https://github.com/zkyseu/PPlanedet/assets/32978636/a70fabce-7f63-45e9-98f8-d93551349640)
![image](https://github.com/zkyseu/PPlanedet/assets/32978636/fef2cc17-2b39-4ffe-9d15-3b7c26e6d200)

原谅我的怨气，整了一个晚上，没一个出结果。。。。

**Comment by hao1305430263** [comment]
![image](https://github.com/zkyseu/PPlanedet/assets/32978636/d4a032f7-fd66-488c-8589-8031929cdf3c)
![image](https://github.com/zkyseu/PPlanedet/assets/32978636/868a74d2-df2d-41e6-845f-a28ef57f4076)
还有这样的。。

使用的代码库是 v5 版本。

**Comment by hao1305430263** [comment]
![image](https://github.com/zkyseu/PPlanedet/assets/32978636/961d2932-0fdd-446f-9809-7bc95a86a522)
![image](https://github.com/zkyseu/PPlanedet/assets/32978636/b23d280b-52ca-424e-82c9-e0611d306741)
config/ulfd/resnet18_tusimple.py 少了一行代码 cfg 读取会报错，按图修改即可，但是依旧没结果。

**Comment by hao1305430263** [comment]
还是说这个权重的鲁棒性就是非常差。。。

**Comment by zkyseu** [comment]
@hao1305430263 您好，不好意思回复晚了，您首先需要确认一下模型参数是否正确，也就是用CULane或者Tusimple的test set中某一张图片来测试一下，看看是否有效果。其次我观察您的图片，和公开数据集差异较大，效果不会很好。
